stages:
  - build

build:
  stage: build
  tags:
    - signac-runner
  image:
    name: jdrouet/docker-with-buildx:stable
  services:
    - name: docker:19.03.13-beta2-dind
      command: [ "--experimental" ]
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/386,linux/amd64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t ${CI_REGISTRY_IMAGE}:latest .